# Generated by Django 5.2.3 on 2025-07-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='gameType',
            field=models.CharField(choices=[('grid', 'Grid'), ('track', 'Track')], default='grid', max_length=10),
        ),
    ]
